// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn main() -> () {
    let mut _0: ();
    let mut _1: (&usize, &usize);
    let mut _2: &usize;
    let _3: usize;
    let mut _4: &mut std::ops::Range<usize>;
    let mut _5: &mut std::ops::Range<usize>;
    let mut _6: &mut std::ops::Range<usize>;
    let mut _7: std::ops::Range<usize>;
    let mut _8: &usize;
    let _9: usize;
    let _10: &usize;
    let _11: &usize;
    let mut _12: bool;
    let mut _13: bool;
    let mut _14: usize;
    let mut _15: usize;
    let _17: !;
    let mut _18: std::option::Option<std::fmt::Arguments<'_>>;
    let _19: std::result::Result<usize, std::boxed::Box<dyn std::any::Any + std::marker::Send>>;
    let mut _20: bool;
    let mut _21: bool;
    let mut _22: &std::result::Result<usize, std::boxed::Box<dyn std::any::Any + std::marker::Send>>;
    let mut _23: !;
    scope 1 {
        debug left_val => _10;
        debug right_val => _11;
        let _16: core::panicking::AssertKind;
        scope 2 {
            debug kind => _16;
        }
    }
    scope 3 {
        debug r => _19;
    }

    bb0: {
        _7 = std::ops::Range::<usize> { start: const 0_usize, end: const _ };
        _6 = &mut _7;
        _5 = <std::ops::Range<usize> as Iterator>::by_ref(move _6) -> bb1;
    }

    bb1: {
        _4 = _5;
        _3 = <&mut std::ops::Range<usize> as Iterator>::count(move _4) -> bb2;
    }

    bb2: {
        _2 = &_3;
        _9 = const _;
        _8 = &_9;
        _1 = (move _2, move _8);
        _10 = (_1.0: &usize);
        _11 = (_1.1: &usize);
        _14 = (*_10);
        _15 = (*_11);
        _13 = Eq(move _14, move _15);
        _12 = Not(move _13);
        switchInt(move _12) -> [0: bb4, otherwise: bb3];
    }

    bb3: {
        _16 = core::panicking::AssertKind::Eq;
        _18 = Option::<Arguments<'_>>::None;
        _17 = core::panicking::assert_failed::<usize, usize>(move _16, _10, _11, move _18);
    }

    bb4: {
        _19 = catch_unwind::<[closure@ui/iterators/iter-count-overflow-debug.rs:11:33: 11:35], usize>(const ZeroSized: [closure@ui/iterators/iter-count-overflow-debug.rs:11:33: 11:35]) -> bb5;
    }

    bb5: {
        _22 = &_19;
        _21 = Result::<usize, Box<dyn Any + Send>>::is_err(move _22) -> [return: bb6, unwind: bb10];
    }

    bb6: {
        _20 = Not(move _21);
        switchInt(move _20) -> [0: bb8, otherwise: bb7];
    }

    bb7: {
        _23 = core::panicking::panic(const "assertion failed: r.is_err()") -> bb10;
    }

    bb8: {
        drop(_19) -> bb9;
    }

    bb9: {
        return;
    }

    bb10 (cleanup): {
        drop(_19) -> [return: bb11, unwind terminate];
    }

    bb11 (cleanup): {
        resume;
    }
}

fn main::{closure#0}(_1: [closure@ui/iterators/iter-count-overflow-debug.rs:11:33: 11:35]) -> usize {
    let mut _0: usize;
    let mut _2: &mut std::ops::RangeInclusive<usize>;
    let mut _3: &mut std::ops::RangeInclusive<usize>;
    let mut _4: &mut std::ops::RangeInclusive<usize>;
    let mut _5: std::ops::RangeInclusive<usize>;

    bb0: {
        _5 = RangeInclusive::<usize>::new(const 0_usize, const _) -> bb1;
    }

    bb1: {
        _4 = &mut _5;
        _3 = <RangeInclusive<usize> as Iterator>::by_ref(move _4) -> bb2;
    }

    bb2: {
        _2 = _3;
        _0 = <&mut RangeInclusive<usize> as Iterator>::count(move _2) -> bb3;
    }

    bb3: {
        return;
    }
}
