// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn main() -> Result<(), std::io::Error> {
    let mut _0: std::result::Result<(), std::io::Error>;

    bb0: {
        _0 = Result::<(), std::io::Error>::Ok(const ());
        return;
    }
}
