thread 'main' panicked at 'try to catch me', ui/panic-runtime/abort.rs:29:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'assertion failed: s.unwrap().code() != Some(0)', ui/panic-runtime/abort.rs:42:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
